# Generated by Django 4.0 on 2021-12-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(auto_now=True)),
                ('duration', models.IntegerField(default=90)),
                ('day', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(auto_now=True)),
                ('date_start', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('duration', models.IntegerField(default=90)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('planned_lesson', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plannedlesson')),
                ('present_students', models.ManyToManyField(related_name='lessons', to='main.Student')),
            ],
        ),
    ]
