# Generated by Django 4.0 on 2022-06-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_company_c_s_min_company_c_t_min_company_p_s_ser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='complexity',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professionalism',
            field=models.IntegerField(default=50),
        ),
    ]
