# Generated by Django 4.0 on 2022-06-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_complexity_teacher_professionalism'),
        ('authsys', '0002_userprofile_info_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_company_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_dont_need_it', to='main.companyuser'),
        ),
    ]
